# Generated by Django 3.2 on 2022-02-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0002_caketype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cake',
            options={'verbose_name': "To'rt", 'verbose_name_plural': "To'rtlar"},
        ),
        migrations.AddField(
            model_name='cake',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cakeapp.caketype', verbose_name='Turi'),
        ),
    ]
