# Generated by Django 3.2 on 2022-02-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0003_auto_20220226_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.caketype', verbose_name='Turi'),
        ),
    ]
