# Generated by Django 3.2 on 2022-02-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0004_alter_cake_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='min_amount_kg',
            field=models.PositiveIntegerField(default=1, verbose_name='Eng kam buyurtma miqdori (kg)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cake',
            name='price_for_kg',
            field=models.FloatField(default=1, verbose_name='1 kg narxi'),
            preserve_default=False,
        ),
    ]
