# Generated by Django 3.2 on 2022-02-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0005_auto_20220226_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='cake',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='cake',
            name='type_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakeapp.caketype', verbose_name='Turi'),
        ),
        migrations.AddField(
            model_name='cake',
            name='type_uz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cakeapp.caketype', verbose_name='Turi'),
        ),
    ]
