# Generated by Django 3.2 on 2022-02-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0006_auto_20220226_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='type_ru',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='type_uz',
        ),
        migrations.AddField(
            model_name='caketype',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='caketype',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='cake',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='caketype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
