# Generated by Django 3.2 on 2022-02-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0009_auto_20220227_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='image',
            field=models.ImageField(default=1, upload_to="To'rtlar", verbose_name='Rasm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filling',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Nachinka', verbose_name='Rasm'),
        ),
    ]
