# Generated by Django 3.2 on 2022-02-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0014_alter_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Holati'),
        ),
    ]
