# Generated by Django 3.2 on 2022-02-28 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0015_contact_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Qaysi kunga')),
                ('number', models.CharField(max_length=13, verbose_name='Telefon raqam')),
                ('how_many_kg', models.PositiveIntegerField(verbose_name='Kerakli hajim (kg)')),
                ('writing', models.CharField(max_length=255, verbose_name="To'rt ustidagi yozuv")),
                ('type_of_delivery', models.PositiveIntegerField(choices=[(1, 'Olib ketish'), (2, 'Yetkazib berish')], default=1, verbose_name='Yetkazib berish turi')),
                ('filling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cakeapp.filling', verbose_name='Nachinka')),
            ],
        ),
    ]
