# Generated by Django 3.2 on 2022-02-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0017_auto_20220228_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='caketype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to="To'rt turlari", verbose_name='Rasm'),
        ),
    ]
