# Generated by Django 3.2 on 2022-02-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0018_caketype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caketype',
            name='image',
            field=models.ImageField(default=1, upload_to="To'rt turlari", verbose_name='Rasm'),
            preserve_default=False,
        ),
    ]
