# Generated by Django 3.2 on 2022-03-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0022_alter_cake_price_for_kg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='Biznig-ishlar', verbose_name='Rasm'),
        ),
    ]
