# Generated by Django 3.2 on 2022-03-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0023_alter_portfolio_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='adress',
            field=models.CharField(default=1, max_length=250, verbose_name='Joylashuv manzili'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
