# Generated by Django 3.2 on 2022-03-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cakeapp', '0025_auto_20220318_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.URLField(default=1, verbose_name='Instagram uchun link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='telegram',
            field=models.URLField(default=1, verbose_name='Telegram uchun link'),
            preserve_default=False,
        ),
    ]
